In [16]:
#1 код первой задачи

matrix = [[1,2,3], [4,5,6], [7,8,9]]

def transpose_matrix(matrix): #принимаем на вход матрицу в виде вложенных списков
    import numpy as np #импортируем библиотеку numpy и создаем объект np
    arr_matrix = np.array(matrix) #преобразуем матрицу в масссив numpy
    arr_transpose = arr_matrix.transpose() #транспонируем массив(меняем местами строки и столбцы)
    
    return arr_transpose

print(transpose_matrix(matrix))

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [27]:
#2 код второй задачи

data = [('Муся', 7, 'Игорь', 'Бероев'), ('Изольда', 2, 'Игорь', 'Бероев'), ('Боба', 3, 'Елена', 'Иванова')]

def optimize_data(animals): #принимаем список кортежей
    
    dict = {} #создаем словарь, который будет хранить информацию 
    
    for animal in animals:
        name, age, owner_name, owner_surname = animal #для каждого животного в списке извлекаем его имя, возраст, имя и фамилию хозяина
        if (owner_name, owner_surname) not in dict: #если имя и фамилия хозяина еще не встречались в словаре
            dict[(owner_name, owner_surname)] = [] #то создаем пустой список для данных об этом хозяине
        dict[(owner_name, owner_surname)].append((name, age)) #добавляем данные о животном в список данных об этом хозяине
    
    return dict

print(optimize_data(data))

{('Игорь', 'Бероев'): [('Муся', 7), ('Изольда', 2)], ('Елена', 'Иванова'): [('Боба', 3)]}


In [22]:
#3 код третьей задачи

import re #импортируем модуль re для работы с регулярными выражениями

def rarest(string): 
    string = re.sub(r'[^\w\s]', '', string.lower()) #приводим строку к нижнему регистру и удаляем знаки препинания
    #где ^ - "не", \w - любой букв и цифр символ, и _, \s - любой пробельный символ
    words = {} #создаем пустой словарь
    for word in string.split(): #в строке ищем слова с помощью split, который делит строку по пробелам и создает список слов
        if word in words: #если слово из списка есть в словаре
            words[word] += 1 #то к его значению добавлаяем 1
        else: #если нет
            words[word] = 1 #то слово добавляем в словарь со значением 1
    min_count = min(words.values()) #находим наименьшее количество повторений 
    rarest_words = [] #создаем пустой список, который будет хранить редкие слова
    for word, count in words.items(): #для каждого слова и его кол-ва повторений проверяем
        #равно ли кол-во повторений наименьшему кол-ву
        if count == min_count: #если да
            rarest_words.append(word) #то слово добавляем в список rarest_words
    return min(rarest_words) 

string = 'у меня есть кот кот, есть собака, у тебя есть попугай'
print(rarest(string))

меня


In [133]:
#4 код четвертой задачи

import re #импортируем модуль re для работы с регулярными выражениями

def mostly(string):
    string = re.sub(r'[^\w\s]', '', string.lower()) #приводим строку к нижнему регистру и удаляем знаки препинания
    letters = {} #создаем пустой словарь
    for letter in string: #перебираем все символы в строке и проверяем
        if letter.isalpha(): #является ли символ буквой
            if letter in letters: #если да, то проверяем, есть ли символ в словаре
                letters[letter] += 1 #если есть, то к его значению добавляем 1
            else: 
                letters[letter] = 1 #если нет, то символ добавляем в словарь со значением 1
    max_count = max(letters.values()) #находим максимальное значение из всех значений словаря
    max_letters = [] #создаем пустой список, который будет хранить буквы с максимальным значением
    for letter, count in letters.items(): #перебираем все буквы и значения 
        if count == max_count: #если значение равно максимальному значению, найденному на предыдущем этапе
            max_letters.append(letter) #добавляем  в список
    return min(max_letters) #возвращаем букву с наименьшим алфавитным значением

string = 'Я люблю ЧАК-чАк'
print(mostly(string))

а


In [134]:
#5 код пятой задачи

string = 'ежу хуже'

def palindrome(string):
    string = string.replace(' ', '') #удаляем все пробелы и оставляем только буквенные символы
    #проверяем длину строки
    if len(string) <= 1: #если она <= 1, то строка является палиндромом
        return True 
    else:
        if string[0] == string[-1]: #проверяем на равенство первый и последний символ строки, если они совпадают
            return palindrome(string[1:-1]) #то из строки удаляем первый и последний символы, и функция вызывает себя с новой строкой
        else:
            return False

print(palindrome(string))

True


In [135]:
#6 код шестой задачи

array = [1, 2, 3, 4, 1, 3, 3, 2, 1, 5]

def sorting(array):
    freq = {} #создаем пустой словарь
    for i in array: #проходим по каждому элементу из списка
        if i in freq: #проверяем, есть ли он в словаре
            freq[i] += 1 #если да, то увеличиваем значение на 1
        else:
            freq[i] = 1 #если нет, добавляем его как новый ключ со значением 1
    #создаем новый список и заполняем отсортированными элементами (сначала самые часто встречающиеся, затем - реже встр)
    #если у двух элементов одинаковое кол-во появлений, то они сортируются по их первому появлению
    sorted_array = sorted(array, key=lambda x: (-freq[x], array.index(x))) 
    return sorted_array

print(sorting(array))

[1, 1, 1, 3, 3, 3, 2, 2, 4, 5]


In [136]:
#7 код седьмой задачи

s = 'мне 22 года меня зовут 2 Маша'

def sequence(s):
    words = s.split() #разбиваем строку на слова и записываем эти слова в words
    for i in range(len(words) - 2): #перебираем все возможные комбинации из трех слов
        #проверяем, состоят ли текущее слово и два следующих за ним слова только из букв
        if words[i].isalpha() and words[i+1].isalpha() and words[i+2].isalpha(): 
            return True
    return False

print(sequence(s))

True


In [137]:
#8 код восьмой задачи

s = 'ообббббббббббрррааааааз'

def max_len(s):
    maxi = 0 #максимальная длина
    curr = 1 #текущая длина
    for i in range(1, len(s)): #проходим по каждому элементу строки, начиная со второго
        if s[i] == s[i-1]: #проверяем, равен ли текущий элемент предыдущему
            curr += 1 #если да, значит эти символы образуют последовательность, для этого увеличиваем значение переменной на 1
        else: #если нет, значит текущая последовательность закончилась
            maxi = max(maxi, curr) #находим максимальное значение между maxi и curr 
            curr = 1 #присваиваем значение 1, чтобы начать считать длину новой последовательности
    return max(maxi, curr)

print(max_len(s))

11


In [138]:
#9 код девятой задачи

ex = '125/5'

def calculate(ex):
    return eval(ex)

print(calculate(ex))

25.0


In [139]:
#10 код десятой задачи

lst = [{'a': 1, 'b': 2, 'c': 3}, {'a': 4, 'd': 5}, {'b': 6, 'e': 7}]

def sum_dicts(lst):
    result = {} #создаем пустой словарь, который будет хранить результаты вычислений
    for d in lst: #проходим по каждому словарю в списке
        for key, value in d.items(): #проходим по каждой паре ключ-значения в текущем словаре
            if key in result: #проверяем, содержится ли ключ в словаре result
                result[key] += value #если да, то его значение увеличивается на значение текущего ключа
            else:
                result[key] = value #если нет, то в него записывается значение ключа
    return result

print(sum_dicts(lst))

{'a': 5, 'b': 8, 'c': 3, 'd': 5, 'e': 7}
